/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.databus2.core.container.monitoring.events;

@SuppressWarnings("all")
/** Total container traffic (inbound or outbound) statistics */
public class ContainerTrafficTotalStatsEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"ContainerTrafficTotalStatsEvent\",\"namespace\":\"com.linkedin.databus.monitoring.events.container\",\"fields\":[{\"name\":\"containerId\",\"type\":\"int\",\"doc\":\"The id of the container that generated the event\"},{\"name\":\"timestampLastResetMs\",\"type\":\"long\",\"doc\":\"unix timestamp of the last reset() call\"},{\"name\":\"timeSinceLastResetMs\",\"type\":\"long\",\"doc\":\"time in ms since the last reset() call\"},{\"name\":\"dimension\",\"type\":\"string\",\"doc\":\"dimension\"},{\"name\":\"numBytes\",\"type\":\"long\",\"doc\":\"number of bytes sent\"},{\"name\":\"numOpenConns\",\"type\":\"long\",\"doc\":\"number of connections open\"},{\"name\":\"numClosedConns\",\"type\":\"long\",\"doc\":\"number of connections closed\"},{\"name\":\"numClients\",\"type\":\"int\",\"doc\":\"number of distinct clients that have connected\"},{\"name\":\"timeClosedConnLifeMs\",\"type\":\"long\",\"doc\":\"total lifespan of closed connections \"},{\"name\":\"timeOpenConnLifeMs\",\"type\":\"long\",\"doc\":\"total lifespan of currently open connections \"},{\"name\":\"errorTotalCount\",\"type\":\"long\",\"doc\":\"total number of networking errors\"},{\"name\":\"errorConnectCount\",\"type\":\"long\",\"doc\":\"connection refused networking errors\"},{\"name\":\"errorTimeoutCount\",\"type\":\"long\",\"doc\":\"connection timeout networking errors\"}]}");
  /** The id of the container that generated the event */
  public int containerId;
  /** unix timestamp of the last reset() call */
  public long timestampLastResetMs;
  /** time in ms since the last reset() call */
  public long timeSinceLastResetMs;
  /** dimension */
  public java.lang.CharSequence dimension;
  /** number of bytes sent */
  public long numBytes;
  /** number of connections open */
  public long numOpenConns;
  /** number of connections closed */
  public long numClosedConns;
  /** number of distinct clients that have connected */
  public int numClients;
  /** total lifespan of closed connections  */
  public long timeClosedConnLifeMs;
  /** total lifespan of currently open connections  */
  public long timeOpenConnLifeMs;
  /** total number of networking errors */
  public long errorTotalCount;
  /** connection refused networking errors */
  public long errorConnectCount;
  /** connection timeout networking errors */
  public long errorTimeoutCount;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return containerId;
    case 1: return timestampLastResetMs;
    case 2: return timeSinceLastResetMs;
    case 3: return dimension;
    case 4: return numBytes;
    case 5: return numOpenConns;
    case 6: return numClosedConns;
    case 7: return numClients;
    case 8: return timeClosedConnLifeMs;
    case 9: return timeOpenConnLifeMs;
    case 10: return errorTotalCount;
    case 11: return errorConnectCount;
    case 12: return errorTimeoutCount;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: containerId = (java.lang.Integer)value$; break;
    case 1: timestampLastResetMs = (java.lang.Long)value$; break;
    case 2: timeSinceLastResetMs = (java.lang.Long)value$; break;
    case 3: dimension = (java.lang.CharSequence)value$; break;
    case 4: numBytes = (java.lang.Long)value$; break;
    case 5: numOpenConns = (java.lang.Long)value$; break;
    case 6: numClosedConns = (java.lang.Long)value$; break;
    case 7: numClients = (java.lang.Integer)value$; break;
    case 8: timeClosedConnLifeMs = (java.lang.Long)value$; break;
    case 9: timeOpenConnLifeMs = (java.lang.Long)value$; break;
    case 10: errorTotalCount = (java.lang.Long)value$; break;
    case 11: errorConnectCount = (java.lang.Long)value$; break;
    case 12: errorTimeoutCount = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
