/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.databus.client.monitoring.events;

@SuppressWarnings("all")
/** Callback statistics */
public class CallbackStatistics extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"CallbackStatistics\",\"namespace\":\"com.linkedin.databus.client.monitoring.events\",\"fields\":[{\"name\":\"count\",\"type\":\"int\",\"doc\":\"number of calls\"},{\"name\":\"successCount\",\"type\":\"int\",\"doc\":\"number of successful calls\"},{\"name\":\"failureCount\",\"type\":\"int\",\"doc\":\"number of unsuccessful calls\"},{\"name\":\"errorCount\",\"type\":\"int\",\"doc\":\"number of calls throwing an exception\"},{\"name\":\"timeCount\",\"type\":\"int\",\"doc\":\"number of calls that timedout\"},{\"name\":\"time\",\"type\":\"long\",\"doc\":\"total call time\"},{\"name\":\"errors\",\"type\":{\"type\":\"map\",\"values\":\"int\"},\"doc\":\"exceptions observed\"}]}");
  /** number of calls */
  public int count;
  /** number of successful calls */
  public int successCount;
  /** number of unsuccessful calls */
  public int failureCount;
  /** number of calls throwing an exception */
  public int errorCount;
  /** number of calls that timedout */
  public int timeCount;
  /** total call time */
  public long time;
  /** exceptions observed */
  public java.util.Map<java.lang.CharSequence,java.lang.Integer> errors;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return count;
    case 1: return successCount;
    case 2: return failureCount;
    case 3: return errorCount;
    case 4: return timeCount;
    case 5: return time;
    case 6: return errors;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: count = (java.lang.Integer)value$; break;
    case 1: successCount = (java.lang.Integer)value$; break;
    case 2: failureCount = (java.lang.Integer)value$; break;
    case 3: errorCount = (java.lang.Integer)value$; break;
    case 4: timeCount = (java.lang.Integer)value$; break;
    case 5: time = (java.lang.Long)value$; break;
    case 6: errors = (java.util.Map<java.lang.CharSequence,java.lang.Integer>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
